[package]
name = "chess-move-debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chess = "3.2.0"
# chessie = "0.1.0"
chessie = { path = "../../brogle/chessie" }
clap = { version = "4.5.18", features = ["derive"] }
